[build]
  command = "npm run build"
  publish = "client/dist/public" #change to public
  functions = "server" #important

[dev]
  framework = "#custom"

[build.environment]
  NPM_FLAGS = "--platform=linux --arch=x64"

